### ISSUE TITLE
Missing releases 0.6.0.0, 0.6.0.1, 0.6.0.2 and 0.6.1.0

### ISSUE THREAD

**Issue by asr** [haskell/zlib#1]
I know this repository is work in progress, but the Hackage releases [0.6.0.0](http://hackage.haskell.org/package/zlib-0.6.0.0), [0.6.0.1](http://hackage.haskell.org/package/zlib-0.6.0.1), [0.6.0.2](http://hackage.haskell.org/package/zlib-0.6.0.2) and [0.6.1.0](http://hackage.haskell.org/package/zlib-0.6.1.0) are missing in this repository.

**Comment by hvr** [comment]
That's due to a bug (not sure if it's known upstream yet) in `darcs` turning *some* darcs tags into Git comments insead of tags, like e.g.
8c71422327dae6edde11a8f5b2215b3da0c994df

**Comment by asr** [comment]
Right, I could reproduce the problem. I filed Darcs' issue [2466](http://bugs.darcs.net/issue2466).

**Comment by hvr** [comment]
I'm probably just going to add Git tags manually (after verifying they match the respective tarballs reasonably)

**Comment by Bodigrim** [comment]
Since no one put tags in seven years, I doubt it will ever happen.
