### ISSUE TITLE
Missing dependency under CentOS

### ISSUE THREAD

**Issue by leohaskell** [haskell/zlib#13]
Adding zlib to a project's .cabal file leads to:

 Configuring zlib-0.6.1.2...
    Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: Missing dependency on a foreign
    library:
    * Missing (or bad) header file: zlib.h
    * Missing C library: z

OS: CentOS release 6.8

**Comment by hvr** [comment]
@leohaskell in order to compile zlib on non-windows OS, it is expected that you have the zlib devel package installed. If  memory serves me right, on RH systems the package you need should be called `zlib-devel`

**Comment by leohaskell** [comment]
@hvr, I've already come to that solution, I just thought, that the zlib.h in the package, would be sufficient to build the haskell library without having the zlib library installed.

**Comment by hvr** [comment]
The included `zlib.h` belongs to the included zlib source-tree which is only ever used on windows. It wouldn't make sense to use it otherwise, as the system-wide zlib library doesn't necessarily match the `zlib.h` header included.
