### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by bgamari** [haskell/zlib#17]
A release with @angerman's cross-compilation work would be appreciated.

**Comment by alexanderkjeldaas** [comment]
Soon it'll be 4 months overdue..

**Comment by angerman** [comment]
@hvr ping?

**Comment by hvr** [comment]
resolved via http://hackage.haskell.org/package/zlib-0.6.2

**Comment by angerman** [comment]
:tada: ... and I’ve just been complaining about this at the Meetup yesterday ;-) recording will follow :-)
