### ISSUE TITLE
GHC 8.8 issue: fail is no longer a member of Monad.

### ISSUE THREAD

**Issue by ekmett** [haskell/zlib#24]
```
Codec/Compression/Zlib/Stream.hsc:377:3: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
377 |   fail   = (finalise >>) . failZ
    |   ^^^^
```

This currently blocks things like compiling `cabal-install` with ghc 8.8 for use with ghc 8.8.

**Comment by ekmett** [comment]
This appears fixed in HEAD, but not on hackage yet.

**Comment by asr** [comment]
Blocking https://github.com/agda/agda/issues/3725.

**Comment by asr** [comment]
GHC 8.8.1-rc1 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2019-July/017944.html). I could compile the upstream version (71f71a517755fd63978da50e21d1d340357ca910) with this version of GHC. Could someone make a release, please.

**Comment by hvr** [comment]
@asr GHC 8.8.1 got released today, so here we go: http://hackage.haskell.org/package/zlib-0.6.2.1 :-)
