### ISSUE TITLE
Support for bytestring 0.11

### ISSUE THREAD

**Issue by sjakobi** [haskell/zlib#36]
AFAIK no code changes are required – only the upper bound needs to be bumped.

**Comment by Minoru** [comment]
It builds, but tests can't be built since `text` still requires `bytestring < 0.11`. That bound [has been bumped](https://github.com/haskell/text/pull/296), but it wasn't released yet.

**Comment by Minoru** [comment]
Actually, `cabal test --enable-tests --constraint 'bytestring == 0.11.0.0' --allow-newer` passes, so I'll just go ahead and submit a PR here.

**Comment by kozross** [comment]
Any news on this?

**Comment by Minoru** [comment]
Just waiting for #37 to get merged.
