### ISSUE TITLE
Increase Cabal upper bound to <3.3

### ISSUE THREAD

**Issue by ezzieyguywuf** [haskell/zlib#38]
The latest cabal is `3.2.1.0`, and the current upper bound of `3.1` forces the use of the older Cabal.

**Comment by andreasabel** [comment]
Could you please elaborate, @ezzieyguywuf ?

I managed to build `zlib` with cabal-install `3.5.0.0`, and I didn't notice any upper bound on Cabal in [zlib.cabal](https://github.com/haskell/zlib/blob/94c31ce43814a967645487591a741c30f53f1a38/zlib.cabal).
