### ISSUE TITLE
tasty-1.5 not accepted

### ISSUE THREAD

**Issue by ysangkok** [haskell/zlib#59]
Seems like https://hackage.haskell.org/package/zlib-0.6.3.0/src/zlib.cabal does not accept tasty-1.5. It would be nice to allow this as it would get us closer to solving

* https://github.com/commercialhaskell/stackage/issues/7111

**Comment by andreasabel** [comment]
Fixed by revision 4: https://hackage.haskell.org/package/zlib-0.6.3.0/revisions/
